[package]
name = "intuitive_examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.22"
clap = { version = "3.2.20", features = ["derive"] }
intuitive = { path = "../intuitive", features = ["experimental"] }
